apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
        - name: ml-pipeline
          image: us-central1-docker.pkg.dev/ml-pipeline-499012/ml-pipeline-repo/ml-pipeline:1.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
